# Generated by Django 5.0.6 on 2026-03-09 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('clan', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=255)),
                ('insignia', models.CharField(blank=True, max_length=255)),
                ('fita', models.CharField(blank=True, max_length=255)),
                ('patente', models.CharField(blank=True, max_length=255)),
                ('banner_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=32, unique=True)),
                ('avatar', models.CharField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_nick', models.CharField(blank=True, max_length=50)),
                ('game_clan', models.CharField(blank=True, max_length=50)),
                ('game_rank', models.CharField(blank=True, max_length=50)),
                ('game_rank_idx', models.IntegerField(default=0)),
                ('pvp_em', models.FloatField(default=0.0)),
                ('pvp_win_rate', models.FloatField(default=0.0)),
                ('pvp_matches', models.IntegerField(default=0)),
                ('pvp_hours', models.IntegerField(default=0)),
                ('pvp_best_rank_rp', models.IntegerField(default=0)),
                ('pvp_best_rank_name', models.CharField(blank=True, max_length=50)),
                ('pve_em', models.FloatField(default=0.0)),
                ('pve_win_rate', models.FloatField(default=0.0)),
                ('pve_matches', models.IntegerField(default=0)),
                ('pve_mission_easy', models.IntegerField(default=0)),
                ('pve_mission_medium', models.IntegerField(default=0)),
                ('pve_mission_hard', models.IntegerField(default=0)),
                ('pve_hours', models.IntegerField(default=0)),
                ('pvp_classes', models.JSONField(blank=True, default=list)),
                ('pve_classes', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
