# Generated by Django 5.0.6 on 2026-03-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_pve_em_alter_userprofile_pve_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='my_fitas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_insignias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_marcas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
