# Generated by Django 5.0.6 on 2026-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_my_fitas_userprofile_my_insignias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pve_win_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pvp_win_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
