# Generated by Django 5.0.6 on 2026-03-11 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_supportticket_ticketresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='subject',
            new_name='name',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('revisao_pvp', 'Revisão de dados PVP'), ('revisao_pve', 'Revisão de dados PVE'), ('conquistas', 'Minhas conquistas'), ('migracao', 'Migração parcial para o Warchaos'), ('bug', 'Reportar Bug'), ('sugestao', 'Sugerir melhorias')], default='revisao_pvp', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'Aguardando Atendimento'), ('in_progress', 'Em Atendimento'), ('resolved', 'Resolvido'), ('unsolved', 'Sem Solução')], default='waiting', max_length=20),
        ),
    ]
