# Generated by Django 5.0.6 on 2026-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='last_viewed_by_staff',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_viewed_by_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
