# Generated by Django 5.0.6 on 2026-03-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_supportticket_last_viewed_by_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='warchaos_migrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='warchaos_solicitou',
            field=models.BooleanField(default=False),
        ),
    ]
