# Generated by Django 5.0.6 on 2026-03-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_warchaos_migrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='warchaos_solicitou_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
