# Generated by Django 5.0.6 on 2026-03-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_warchaos_solicitou_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='warchaos_nick',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='warchaos_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
