# Generated by Django 5.0.6 on 2026-03-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_warchaos_nick_userprofile_warchaos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='hide_empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='rank_level',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
