# Generated by Django 5.0.6 on 2026-04-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_banner_hide_empty_banner_rank_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_challenges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
