server {
    listen 80;
    server_name warbanner.italommf.com.br;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para o Backend (API)
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy para Media (Imagens)
    location /media/ {
        proxy_pass http://backend:8000/media/;
        proxy_set_header Host $host;
    }
}
