# Generated by Django 5.0.6 on 2026-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_uploadedimage_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image_type',
            field=models.CharField(choices=[('pvp', 'PvP'), ('pve', 'PvE'), ('desafios', 'Desafios')], default='desafios', max_length=10),
        ),
    ]
