# Generated by Django 5.0.6 on 2026-03-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_uploadedimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='debug_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads_debug/'),
        ),
    ]
