# Generated by Django 5.0.6 on 2026-03-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_uploadedimage_debug_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(help_text='Texto exatamente como lido pelo OCR (normalizado)', max_length=255, unique=True)),
                ('correct_item_id', models.CharField(help_text='ID/Filename do desafio correto', max_length=255)),
                ('category', models.CharField(help_text='marcas, insignias ou fitas', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
